Repository Pusan21/Elecvery-Clone-Backend, pull requests merged in 2022-10, with the labels that each got.

#11 docs: 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/pull_request_template.md
Labels: documentation, chore

#13 docs: 리드미 작성
  README.md
Labels: documentation, chore

#15 충전소 repository 개발
  src/main/java/com/Pusan21/ElecveryCloneBackend/ElecveryCloneBackendApplication.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/controller/PingPongController.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/Customer.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/CustomerPaymentInformation.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/Manager.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/Reservation.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/Station.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/StationLocation.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/StationSlot.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/repository/StationRepository.java
  src/test/java/com/Pusan21/ElecveryCloneBackend/ElecveryCloneBackendApplicationTests.java
  src/test/java/com/Pusan21/ElecveryCloneBackend/repository/StationRepositoryTest.java
  src/test/java/com/Pusan21/ElecveryCloneBackend/repository/StationRepositoryTestHelper.java
Labels: feature, test

#16 DB refactor
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/Customer.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/CustomerPaymentInformation.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/Member.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/Member_Station.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/PaymentInformation.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/Reservation.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/Station.java
Labels: refactor

#17 fix: conflict 해결
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/Manager.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/Member.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/PaymentInformation.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/Reservation.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/Station.java
Labels: bug

#25 내 카드 관리 api 개발
  build.gradle
  src/main/java/com/Pusan21/ElecveryCloneBackend/controller/PaymentInformationController.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/dto/PaymentInformationDto.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/PaymentInformation.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/repository/PaymentInformationRepository.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/service/PaymentInformationService.java
  src/main/resources/application.yml
  src/test/java/com/Pusan21/ElecveryCloneBackend/helper/PaymentInformationRepositoryTestHelper.java
  src/test/java/com/Pusan21/ElecveryCloneBackend/helper/PaymentInformationServiceTestHelper.java
  src/test/java/com/Pusan21/ElecveryCloneBackend/helper/StationRepositoryTestHelper.java
  src/test/java/com/Pusan21/ElecveryCloneBackend/repository/PaymentInformationRepositoryTest.java
  src/test/java/com/Pusan21/ElecveryCloneBackend/repository/StationRepositoryTest.java
  src/test/java/com/Pusan21/ElecveryCloneBackend/service/PaymentServiceTest.java
Labels: chore, feature, test

#27 Mycar entity added
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/Member.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/Mycar.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/Reservation.java
Labels: feature

#30 충전소 공공데이터포털 연결하기
  build.gradle
  libs/json-20220924.jar
  src/main/java/com/Pusan21/ElecveryCloneBackend/controller/StationController.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/Station.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/StationLocation.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/entity/StationSlot.java
  src/main/java/com/Pusan21/ElecveryCloneBackend/service/StationService.java
  src/test/java/com/Pusan21/ElecveryCloneBackend/helper/StationRepositoryTestHelper.java
  src/test/java/com/Pusan21/ElecveryCloneBackend/repository/StationRepositoryTest.java
Labels: chore, feature, test
